// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LEARN_TitleMenu","status":true,"description":"","parameters":{}},
{"name":"LEARN_Teleport","status":true,"description":"用于制作传送道具和传送技能。(v1.0)","parameters":{"Teleport Start AnimationId":"117","Teleport End AnimationId":"120"}}
];
